# Generated by Django 5.1 on 2025-10-30 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID_prd', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=100)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to='img_productos/')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ID_Prove', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True)),
                ('ID_prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='app_inventario.producto', verbose_name='Producto Suministrado')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
